
#k's that are analyzed for k-mer based approaches
ks : [11, 13, 15, 17, 19]

#fraction (between 0 and 1) of reads that need to support a variant for it to be labeled homozygous
thresholdHomCall : 0.85

thresholdHomCall_coverage : 50

#Generate k-mer profiles (and histograms) based on ks and soft-clipped reads from alignments
generateKmerProfiles: True

#Generate gfa files for each barcode
generateGFAs: False

performQualityControl: False

performCorrections: True
correctionMinKmer: 11
correctionMaxKmer: 19
correctionKmerStep: 2

generatePangenome: False

pangenomeVariantCalling: False

#if True, only use the given subset of run folders
useSubsetOfRuns: True
runs: [corona_03_11]

#if True only use the given subset of barcodes
useSubsetOfBarcodes: True
barcodes: 
  corona_03_11: ['01', '04', '09']
