
#k's that are analyzed for k-mer based approaches
ks : [11]

#fraction (between 0 and 1) of reads that need to support a variant for it to be labeled homozygous
thresholdHomCall : 0.85

thresholdHomCall_coverage : 50

#Generate k-mer profiles (and histograms) based on ks and soft-clipped reads from alignments
generateKmerProfiles: False

#Generate gfa files for each barcode
generateGFAs: False

performQualityControl: False

performCorrections: False
kmerUseForCorrections: [11, 19]

generatePangenome: False

pangenomeVariantCalling: True

#if True, only use the given subset of run folders
useSubsetOfRuns: True
runs: [corona_03_11]

#if True only use the given subset of barcodes
useSubsetOfBarcodes: True
barcodes: 
  corona_03_11 : ['01','04','09']
